app:
  message: Message sent to the RabbitMQ queue Successfully
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: project
    queue: project
    routingKey: project